In [2]:
import numpy as np
import time

In [3]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
#execution performance
size = 100_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#numpy array


python list time = 0.014046669006347656 seconds


In [6]:
#import sys
#print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
#print(f"numpy array size = {np_arr.nbytes} bytes")


In [11]:
#numpy array   ---->  create from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype)

arr2 = np.array([1,2,3,4,5, "prime"])
print(arr2, type(arr2), arr.dtype)

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d, arr2d.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> int64
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [17]:
#create 
arr1 = np.zeros((2,3), dtype="int64")
print(arr1, arr1.shape)

arr2 = np.ones((5, 2)) #prefill
print(arr2, arr2.shape)

arr3 = np.full((2,3), 100) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3,4) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1,11)  #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,4) #evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] (5, 2)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] (3, 4)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[  1.  34.  67. 100.] (4,)


In [19]:
#multidimensinal array
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(np.sum(arr2d))

sum_of_columns = np.sum(arr2d, axis=0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2d, axis=1)
print(sum_of_rows)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [ ]:
#3d array
