In [3]:
import numpy as np
import time

In [4]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
#execution performance
size = 100_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#numpy array


python list time = 0.016669034957885742 seconds


In [6]:
#import sys
#print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
#print(f"numpy array size = {np_arr.nbytes} bytes")


In [7]:
#numpy array   ---->  create from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype)

arr2 = np.array([1,2,3,4,5, "prime"])
print(arr2, type(arr2), arr.dtype)

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d, arr2d.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> int64
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [8]:
#create 
arr1 = np.zeros((2,3), dtype="int64")
print(arr1, arr1.shape)

arr2 = np.ones((5, 2)) #prefill
print(arr2, arr2.shape)

arr3 = np.full((2,3), 100) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3,4) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1,11)  #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,4) #evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] (5, 2)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] (3, 4)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[  1.  34.  67. 100.] (4,)


In [9]:
#multidimensinal array
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(np.sum(arr2d))

sum_of_columns = np.sum(arr2d, axis=0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2d, axis=1)
print(sum_of_rows)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [12]:
#3d array
arr3d = np.array([[[1,2],[3,4],[5,6]],[[7,8], [9,10], [11,12]]]) #2 * 3 * 2
print(arr3d, arr3d.shape)

#indexing
print(arr3d[1, 1, 0])

#slicing 
print(arr3d[:, 0, :])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]


In [17]:
#vectorization
arr = np.array([1,5,3,4,9])
arr2 = np.array([6,7,8,9,10])
print(arr ** 2)
print(arr + 10)
print(arr + arr2)

[ 1 25  9 16 81]
[11 15 13 14 19]
[ 7 12 11 13 19]


In [18]:
#broadcasting
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])

print(arr.shape)
print(arr2.shape)
print(arr + arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [23]:
#normalize 
arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)  #mean of this is 0 

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
